import { EditEntryType, ValidationType } from "../types/formTypes";

export const registrationFormConfig = {
  title: "User Registration",
  description: "Please fill out the form below to create your account",
  editEntries: [
    {
      attribute: "firstName",
      attributeName: "First Name",
      type: EditEntryType.Text,
      isRequired: true,
      validations: [
        ValidationType.RequiredField,
        ValidationType.TextLengthBelow50,
      ],
    },
    {
      attribute: "lastName",
      attributeName: "Last Name",
      type: EditEntryType.Text,
      isRequired: true,
      validations: [
        ValidationType.RequiredField,
        ValidationType.TextLengthBelow50,
      ],
    },
    {
      attribute: "email",
      attributeName: "Email Address",
      type: EditEntryType.Text,
      isRequired: true,
      validations: [ValidationType.RequiredField, ValidationType.Email],
    },
    {
      attribute: "phoneNumber",
      attributeName: "Phone Number",
      type: EditEntryType.Text,
      isRequired: false,
      validations: [ValidationType.PhoneNumber],
    },
    {
      attribute: "address",
      attributeName: "Home Address",
      type: EditEntryType.Address,
      isRequired: false,
    },
    {
      attribute: "country",
      attributeName: "Country",
      type: EditEntryType.Select,
      options: [
        "United States",
        "Canada",
        "United Kingdom",
        "Australia",
        "Other",
      ],
      isRequired: true,
      validations: [ValidationType.RequiredField],
    },
    {
      attribute: "birthDate",
      attributeName: "Date of Birth",
      type: EditEntryType.Date,
      isRequired: true,
      validations: [ValidationType.RequiredField],
    },
    {
      attribute: "bio",
      attributeName: "About You",
      subName: "Tell us a little about yourself",
      type: EditEntryType.TextArea,
      isRequired: false,
      validations: [ValidationType.TextLengthBelow300],
    },
    {
      attribute: "preferences",
      attributeName: "Communication Preferences",
      type: EditEntryType.Radio,
      isRequired: true,
      options: ["Email", "Phone", "Both"],
      validations: [ValidationType.RequiredField],
    },
    {
      attribute: "skills",
      attributeName: "Skills",
      subName: "List your professional skills",
      type: EditEntryType.TextList,
      isRequired: false,
    },
    {
      attribute: "education",
      attributeName: "Education History",
      subName: "List your degrees and institutions",
      type: EditEntryType.DoubleTextList,
      isRequired: false,
    },
    {
      attribute: "profilePhoto",
      attributeName: "Profile Photo",
      type: EditEntryType.ProfilePhoto,
      isRequired: false,
    },
    {
      attribute: "coverPhoto",
      attributeName: "Cover Photo",
      type: EditEntryType.Photo,
      isRequired: false,
    },
    {
      attribute: "documents",
      attributeName: "Additional Documents",
      type: EditEntryType.File,
      isRequired: false,
    },
    {
      attribute: "photoGallery",
      attributeName: "Photo Gallery",
      type: EditEntryType.FilePhoto,
      isRequired: false,
    },
    {
      attribute: "showcase",
      attributeName: "Portfolio Showcase",
      type: EditEntryType.Showcase,
      extraParam: { isInstagramShowcase: true },
      isRequired: false,
    },
    {
      attribute: "article",
      attributeName: "Personal Statement",
      type: EditEntryType.Article,
      isRequired: false,
    },
    {
      attribute: "monthlyIncome",
      attributeName: "Monthly Income",
      type: EditEntryType.Text,
      isRequired: false,
      validations: [ValidationType.Number],
    },
    {
      attribute: "Interests",
      attributeName: "Current Hobbies",
      subName: "List all your current hobbies",
      type: EditEntryType.PillList,
      isRequired: false,
    },
    {
      attribute: "termsAccepted",
      attributeName: "Terms and Conditions",
      subName: "I agree to the terms and conditions",
      type: EditEntryType.Checkbox,
      isRequired: true,
      validations: [ValidationType.CheckboxChecked],
    },
  ],
  entityObj: {
    firstName: "",
    lastName: "",
    email: "",
    phoneNumber: "",
    address: {},
    country: "United States",
    birthDate: "",
    bio: "",
    preferences: "Email",
    skills: [],
    education: [],
    profilePhoto: "",
    coverPhoto: "",
    documents: [],
    photoGallery: [],
    showcase: {
      title: "",
      handle: "",
      url: "",
      profile_photo_url: "",
      image_urls: [],
    },
    article: {
      title: "",
      subtitle: "",
      content: "",
      image_url: "",
    },
    monthlyIncome: "",
    termsAccepted: false,
  },
  interests: [],
};
